[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
admin_passwd = admin
csv_internal_sep = ,
db_maxconn = 64
db_sslmode = prefer
db_template = template0
http_port = 8069
log_level = info
proxy_mode = True
without_demo = True
limit_time_cpu = 1800
limit_time_real = 1800
limit_time_real_cron = 1800
