databases:
  - name: myndo-db
    plan: free
    databaseName: myndo
    user: odoo

services:
  - type: web
    name: myndo-odoo
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: myndo-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: myndo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: myndo-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: myndo-db
          property: database
